export const additionalBooks = {
  id: "additionalBooks",
  title: "Кошумча китептер",
  type: "group",
  children: [
    {
      id: "spravochnik",
      title: "Справочник",
      type: "item",
      book: "справочник.pdf",
      url: "/koshumcha-kitep/spravochnik",
      children: [
        {
          id: "spravochnik-1",
          title: "Тил илиминин жалпы маселелери",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/1",
          page: 4,
        },
        {
          id: "spravochnik-2",
          title: "Лексикология",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/2",
          page: 8,
        },
        {
          id: "spravochnik-3",
          title: "Фонетика",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/3",
          page: 16,
        },
        {
          id: "spravochnik-4",
          title: "Орфография",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/4",
          page: 35,
        },
        {
          id: "spravochnik-5",
          title: "Морфология",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/5",
          page: 37,
        },
        {
          id: "spravochnik-6",
          title: "Зат атооч",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/6",
          page: 47,
        },
        {
          id: "spravochnik-7",
          title: "Сын атооч",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/7",
          page: 60,
        },
        {
          id: "spravochnik-8",
          title: "Сан атооч",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/8",
          page: 64,
        },
        {
          id: "spravochnik-9",
          title: "Ат атооч",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/9",
          page: 68,
        },
        {
          id: "spravochnik-10",
          title: "Этиш.",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/10",
          page: 73,
        },
        {
          id: "spravochnik-11",
          title: "Тактооч",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/11",
          page: 88,
        },
        {
          id: "spravochnik-12",
          title: "Тууранды сөздөр",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/12",
          page: 93,
        },
        {
          id: "spravochnik-13",
          title: "Сырдык сөздөр",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/13",
          page: 93,
        },
        {
          id: "spravochnik-14",
          title: "Кызматчы сөздөр",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/14",
          page: 93,
        },
        {
          id: "spravochnik-15",
          title: "Жазуу",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/15",
          page: 99,
        },
        {
          id: "spravochnik-16",
          title: "Синтаксис",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/16",
          page: 101,
        },
        {
          id: "spravochnik-17",
          title: "Пунктуация",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/17",
          page: 149,
        },
        {
          id: "spravochnik-18",
          title: "Байланыштуу кеп (речь)",
          type: "item",
          url: "/koshumcha-kitep/spravochnik/18",
          page: 156,
        },
      ],
    },
    {
      id: "jatjazuu",
      title: "Жат жазуулар",
      type: "item",
      book: " жат жазуулар.pdf",
      url: "/koshumcha-kitep/jatjazuu",
      page: 4,
    },
  ],
};
