// ==============================|| MENU ITEMS - UTILITIES ||============================== //

const classes = {
  id: "classes",
  title: "Класстар",
  type: "group",
  children: [
    {
      id: "class5",
      title: "5-класс",
      photo: "5-класс.jpeg",
      description:
        "Окутуу кыргыз тилинде жүргүзүлгөн жалпы билим берүүчү мектептер үчүн окуу китеби",
      type: "item",
      book: "5-класс.pdf",
      url: "/class/class5",
      children: [
        {
          id: "class5-1",
          title: "I ЧЕЙРЕК",
          type: "item",
          url: "/class/class5/1",
          page: 5,
        },
        {
          id: "class5-2",
          title: "II ЧЕЙРЕК",
          type: "item",
          url: "/class/class5/2",
          page: 73,
        },
        {
          id: "class5-3",
          title: "III ЧЕЙРЕК",
          type: "item",
          url: "/class/class5/3",
          page: 107,
        },
        {
          id: "class5-4",
          title: "IV ЧЕЙРЕК",
          type: "item",
          url: "/class/class5/4",
          page: 140,
        },
      ],
    },
    {
      id: "class6",
      title: "6-класс",
      description:
        "Окутуу кыргыз тилинде жүргүзүлгөн жалпы билим берүүчү мектептер үчүн окуу китеби",
      type: "item",
      url: "/class/class6",
      photo: "6-класс.jpeg",
      book: "6-класс.pdf",
      children: [
        {
          id: "class6-1",
          title:
            "V КЛАССТА ӨТҮЛГӨН МАТЕРИАЛДАРДЫ КАЙТАЛОО, ЖАЛПЫЛОО ЖАНА БЫШЫКТОО",
          type: "item",
          url: "/class/class6/1",
          page: 8,
        },
        {
          id: "class6-2",
          title: "БАЙЛАНЫШТУУ КЕП",
          type: "item",
          url: "/class/class6/2",
          page: 18,
        },
        {
          id: "class6-3",
          title: "ЛЕКСИКА, ФРАЗЕОЛОГИЯ, ЛЕКСИКОГРАФИЯ ЖАНА КЕП МАДАНИЯТЫ",
          type: "item",
          url: "/class/class6/3",
          page: 66,
        },
        {
          id: "class6-4",
          title: "СӨЗ ЖАСОО ЖАНА ОРФОГРАФИЯ",
          type: "item",
          url: "/class/class6/4",
          page: 92,
        },
        {
          id: "class6-5",
          title: "ЗАТ АТООЧ",
          type: "item",
          url: "/class/class6/5",
          page: 125,
        },
        {
          id: "class6-6",
          title: "СЫН АТООЧ",
          type: "item",
          url: "/class/class6/6",
          page: 141,
        },
        {
          id: "class6-7",
          title: "САН АТООЧ",
          type: "item",
          url: "/class/class6/7",
          page: 155,
        },
        {
          id: "class6-8",
          title: "АТ АТООЧ",
          type: "item",
          url: "/class/class6/8",
          page: 181,
        },
        {
          id: "class6-9",
          title: "ЭТИШ",
          type: "item",
          url: "/class/class6/9",
          page: 210,
        },
        {
          id: "class6-10",
          title: "6-КЛАССТА ӨТҮЛГӨН МАТЕРИАЛДАРДЫ БЕКЕМДӨӨ ЖАНА БЫШЫКТОО",
          type: "item",
          url: "/class/class6/10",
          page: 239,
        },
      ],
    },
    {
      id: "class7",
      title: "7-класс",
      description:
        "Окутуу кыргыз тилинде жүргүзүлгөн жалпы билим берүүчү мектептер үчүн окуу китеби",
      photo: "7-класс.jpeg",
      type: "item",
      url: "/class/class7",
      book: "7-класс.pdf",
      children: [
        {
          id: "class7-1",
          title: "Байланыштуу кеп",
          type: "item",
          url: "/class/class7/1",
          page: 6,
        },
        {
          id: "class7-2",
          title: "Кептин стилдери",
          type: "item",
          url: "/class/class7/2",
          page: 29,
        },
        {
          id: "class7-3",
          title: "Кептин түрлөрү",
          type: "item",
          url: "/class/class7/3",
          page: 42,
        },
        {
          id: "class7-4",
          title: "Морфология,орфография жана кеп маданияты",
          type: "item",
          url: "/class/class7/4",
          page: 48,
        },
        {
          id: "class7-5",
          title: "Өзгөчө сөз түркүмдөрү жана кеп маданияты",
          type: "item",
          url: "/class/class7/5",
          page: 67,
        },
        {
          id: "class7-6",
          title: "Этиштин өзгөчө формалары жана кеп маданияты",
          type: "item",
          url: "/class/class7/6",
          page: 83,
        },
      ],
    },
    {
      id: "class8",
      title: "8-класс",
      description:
        "Окутуу кыргыз тилинде жүргүзүлгөн жалпы билим берүүчү мектептер үчүн окуу китеби",
      photo: "8-класс.jpeg",
      type: "item",
      url: "/class/class8",
      book: "8-класс.pdf",
      children: [
        {
          id: "class8-1",
          title: "Байланыштуу кеп",
          type: "item",
          url: "/class/class8/1",
          page: 7,
        },
        {
          id: "class8-2",
          title: "Кептин стилдери",
          type: "item",
          url: "/class/class8/2",
          page: 28,
        },
        {
          id: "class8-3",
          title: "Кептин түрлөрү",
          type: "item",
          url: "/class/class8/3",
          page: 44,
        },
        {
          id: "class8-4",
          title: "Сөз айкашынын синтаксиси",
          type: "item",
          url: "/class/class8/4",
          page: 72,
        },
        {
          id: "class8-5",
          title: "Сүйлөмдүн синтаксиси",
          type: "item",
          url: "/class/class8/5",
          page: 101,
        },
        {
          id: "class8-6",
          title: "Жөнөкөй сүйлөмдүн синтаксиси",
          type: "item",
          url: "/class/class8/6",
          page: 115,
        },
        {
          id: "class8-7",
          title: "Айкындооч мүчөлөр",
          type: "item",
          url: "/class/class8/7",
          page: 139,
        },
        {
          id: "class8-8",
          title: "Бир тутумдуу сүйөмдөр",
          type: "item",
          url: "/class/class8/8",
          page: 217,
        },
        {
          id: "class8-9",
          title: "Жыл бою өтүлгөн материалдарды бекемдөө жана бышыктоо",
          type: "item",
          url: "/class/class8/9",
          page: 235,
        },
      ],
    },
    {
      id: "class9",
      title: "9-класс",
      description:
        "Окутуу кыргыз тилинде жүргүзүлгөн жалпы билим берүүчү мектептердин  9-классы үчүн окуу китеби",
      photo: "9-класс.jpeg",
      type: "item",
      url: "/class/class9",
      book: "9-класс.pdf",
      children: [
        {
          id: "class9-1",
          title: "Байланыштуу кеп",
          type: "item",
          url: "/class/class9/1",
          page: 3,
        },
        {
          id: "class9-2",
          title: "Кептин стилдери",
          type: "item",
          url: "/class/class9/2",
          page: 17,
        },
        {
          id: "class9-3",
          title: "Кептин түрлөрү",
          type: "item",
          url: "/class/class9/3",
          page: 32,
        },
        {
          id: "class9-4",
          title: "Сүйлөмдүн обочолонгон түшүндүрмө мүчөлөрү",
          type: "item",
          url: "/class/class9/4",
          page: 90,
        },
        {
          id: "class9-5",
          title: "Синтаксистик татаал конструкциялар",
          type: "item",
          url: "/class/class9/5",
          page: 99,
        },
        {
          id: "class9-6",
          title: "Татаал сүйлөм",
          type: "item",
          url: "/class/class9/6",
          page: 123,
        },
      ],
    },
    {
      id: "class10",
      title: "10-класс",
      description:
        "Окутуу кыргыз тилинде жүргүзүлгөн жалпы билим берүүчү мектептер үчүн окуу китеби",
      type: "item",
      url: "/class/class10",
      book: "10-класс.pdf",
      children: [
        {
          id: "class10-1",
          title: "Байланыштуу кеп",
          type: "item",
          url: "/class/class10/1",
          page: 8,
        },
        {
          id: "class10-2",
          title: "Фонетика, орфография, орфоэпия жана кеп маданияты",
          type: "item",
          url: "/class/class10/2",
          page: 42,
        },
        {
          id: "class10-3",
          title: "Орфография жана орфоэпия",
          type: "item",
          url: "/class/class10/3",
          page: 80,
        },

        {
          id: "class10-4",
          title: "Лексика жана кеп маданияты",
          type: "item",
          url: "/class/class10/4",
          page: 94,
        },

        {
          id: "class10-5",
          title: "Морфология жана кеп маданияты",
          type: "item",
          url: "/class/class10/5",
          page: 134,
        },

        {
          id: "class10-6",
          title: "Синтаксис жана кеп маданияты",
          type: "item",
          url: "/class/class10/6",
          page: 182,
        },

        {
          id: "class10-7",
          title: "10-класста өтүлгөн материалдарды бекемдөө жана бышыктоо",
          type: "item",
          url: "/class/class10/7",
          page: 209,
        },
      ],
    },
    {
      id: "class11",
      title: "11-класс",
      description:
        "Окутуу кыргыз тилинде жүргүзүлгөн жалпы билим берүүчү орто мектептер жана гимназиялар үчүн окуу китеби",
      type: "item",
      url: "/class/class11",
      book: "11-класс.pdf",
      children: [
        {
          id: "class11-1",
          title: "10-класста алган билимдерин эске алуу жана бышыктоо",
          type: "item",
          url: "/class/class11/1",
          page: 9,
        },
        {
          id: "class11-2",
          title: "Байланыштуу кеп",
          type: "item",
          url: "/class/class11/2",
          page: 14,
        },
        {
          id: "class11-3",
          title: "Кыргыз эли колдонгон жазуулар",
          type: "item",
          url: "/class/class11/3",
          page: 68,
        },
        {
          id: "class11-4",
          title: "Фразеология жана кеп маданияты",
          type: "item",
          url: "/class/class11/4",
          page: 80,
        },
        {
          id: "class11-5",
          title: "Кеп маданияты",
          type: "item",
          url: "/class/class11/5",
          page: 98,
        },
        {
          id: "class11-6",
          title: "Кыргыз лексикасынын баюу жолдору",
          type: "item",
          url: "/class/class11/6",
          page: 111,
        },
        {
          id: "class11-7",
          title: "Стиль жана стилистика",
          type: "item",
          url: "/class/class11/7",
          page: 151,
        },
        {
          id: "class11-8",
          title:
            "5-11-класстарда өтүлгөн материалдарды системалыштыруу жана жалпылаштыруу",
          type: "item",
          url: "/class/class11/8",
          page: 156,
        },
      ],
    },
  ],
};

export default classes;
